server:
  port: 9101
spring:
  application:
    name: mb-generator
  profiles:
    active: dev
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    database: tacmgmt
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.212:3306/${spring.datasource.database}?useUnicode=true&characterEncoding=utf-8
    username: tacmgmt
    password: tacmgmt
logging:
  level:
    com.xieyu.mbgenerator: debug
